// Generates shared/codes.generated.ts from the GeoJSON the frontend already ships.
// GDELT uses FIPS 10-4 country codes; Natural Earth carries FIPS_10 on 171 of 177 polygons,
// with every known trap already correct (UK=GB, CH=CN, SZ=CH, AS=AU, AU=AT, GM=DE, ...).
// The override covers the polygons whose FIPS_10 is -99 and the two Palestinian codes.
//   node scripts/gen-codes.ts          write the file
//   node scripts/gen-codes.ts --check  exit 1 if the committed file is out of date
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
import { geoCode } from '../shared/geocode.ts';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const GEOJSON = join(root, 'frontend/public/geo/countries.geojson');
const OUT = join(root, 'shared/codes.generated.ts');

const OVERRIDE: Record<string, string> = { NO: 'NO', IS: 'IL', WE: 'PS', GZ: 'PS', OD: 'SS' };

interface Feature { properties: { ADMIN?: string; FIPS_10?: string; ISO_A2?: string; ISO_A2_EH?: string } }
const features: Feature[] = JSON.parse(readFileSync(GEOJSON, 'utf8')).features;

const fipsToIso: Record<string, string> = {};
const polygonCodes = new Set<string>();
for (const f of features) {
  const iso = geoCode(f.properties);
  if (!iso) continue;                       // Northern Cyprus, Somaliland: no code, unfilled
  polygonCodes.add(iso);
  const fips = f.properties.FIPS_10;
  if (!fips || fips === '-99') continue;
  if (fipsToIso[fips] && fipsToIso[fips] !== iso) {
    throw new Error(`FIPS ${fips} maps to both ${fipsToIso[fips]} and ${iso} (${f.properties.ADMIN})`);
  }
  fipsToIso[fips] = iso;
}
for (const [fips, iso] of Object.entries(OVERRIDE)) {
  if (fipsToIso[fips] && fipsToIso[fips] !== iso) throw new Error(`override ${fips} conflicts with GeoJSON ${fipsToIso[fips]}`);
  fipsToIso[fips] = iso;
}

const sorted = Object.fromEntries(Object.entries(fipsToIso).sort(([a], [b]) => a.localeCompare(b)));
const body =
  `// GENERATED by scripts/gen-codes.ts from frontend/public/geo/countries.geojson. Do not edit.\n` +
  `// ${Object.keys(sorted).length} FIPS codes, ${polygonCodes.size} polygon countries.\n` +
  `export const FIPS_TO_ISO: Readonly<Record<string, string>> = ${JSON.stringify(sorted, null, 2)};\n` +
  `export const POLYGON_CODES: readonly string[] = ${JSON.stringify([...polygonCodes].sort())};\n`;

if (process.argv.includes('--check')) {
  let current = '';
  try { current = readFileSync(OUT, 'utf8'); } catch { /* missing */ }
  if (current !== body) { console.error('shared/codes.generated.ts is out of date; run: node scripts/gen-codes.ts'); process.exit(1); }
  console.log('codes.generated.ts up to date');
} else {
  writeFileSync(OUT, body);
  console.log(`wrote ${OUT}: ${Object.keys(sorted).length} codes, ${polygonCodes.size} polygons`);
}
